// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type First struct {
	ID        int64     `json:"id"`
	Link      string    `json:"link"`
	Price     int64     `json:"price"`
	CreatedAt time.Time `json:"created_at"`
}

type OnSale struct {
	ID        int64     `json:"id"`
	Link      string    `json:"link"`
	Price     int64     `json:"price"`
	SalePer   int64     `json:"salePer"`
	CreatedAt time.Time `json:"created_at"`
}

type Second struct {
	ID        int64     `json:"id"`
	Link      string    `json:"link"`
	Price     int64     `json:"price"`
	CreatedAt time.Time `json:"created_at"`
}
