// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"context"
)

type Querier interface {
	CreateOnSale(ctx context.Context, arg CreateOnSaleParams) (OnSale, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	DeleteOnSale(ctx context.Context, id int64) error
	DeleteProduct(ctx context.Context, id int64) error
	GetLengthOfProducts(ctx context.Context) (int64, error)
	GetLengthOnSale(ctx context.Context) (int64, error)
	GetOnSale(ctx context.Context, id int64) (OnSale, error)
	GetProduct(ctx context.Context, id int64) (Product, error)
	ListOnSale(ctx context.Context, arg ListOnSaleParams) ([]OnSale, error)
	ListProduct(ctx context.Context, arg ListProductParams) ([]Product, error)
	UpdateOnSale(ctx context.Context, arg UpdateOnSaleParams) (OnSale, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
}

var _ Querier = (*Queries)(nil)
