// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	AddOnSaleBalance(ctx context.Context, arg AddOnSaleBalanceParams) (OnSale, error)
	AddSecondBalance(ctx context.Context, arg AddSecondBalanceParams) (Second, error)
	AddfirstBalance(ctx context.Context, arg AddfirstBalanceParams) (First, error)
	CreateFirst(ctx context.Context, arg CreateFirstParams) (First, error)
	CreateOnSale(ctx context.Context, arg CreateOnSaleParams) (OnSale, error)
	CreateSecond(ctx context.Context, arg CreateSecondParams) (Second, error)
	DeleteFirst(ctx context.Context, id int64) error
	DeleteOnSale(ctx context.Context, id int64) error
	DeleteSecond(ctx context.Context, id int64) error
	GetFirst(ctx context.Context, id int64) (First, error)
	GetFirstForUpdate(ctx context.Context, id int64) (First, error)
	GetOnSale(ctx context.Context, id int64) (OnSale, error)
	GetOnSaleForUpdate(ctx context.Context, id int64) (OnSale, error)
	GetSecond(ctx context.Context, id int64) (Second, error)
	GetSecondForUpdate(ctx context.Context, id int64) (Second, error)
	ListFirst(ctx context.Context, arg ListFirstParams) ([]First, error)
	ListOnSale(ctx context.Context, arg ListOnSaleParams) ([]OnSale, error)
	ListSecond(ctx context.Context, arg ListSecondParams) ([]Second, error)
	UpdateFirst(ctx context.Context, arg UpdateFirstParams) (First, error)
	UpdateOnSale(ctx context.Context, arg UpdateOnSaleParams) (OnSale, error)
	UpdateSecond(ctx context.Context, arg UpdateSecondParams) (Second, error)
}

var _ Querier = (*Queries)(nil)
